#
# SERVICE:
#
#       - A Service defines and allows access to a set of Pods chosen using the Label Selector ('app: hello-world'
#         in this case).
#       
#       - By default services load balance traffic to the set of Pods. If your application
#         does not need a load balancer, you can create a 'headless' service by setting 'Cluster IP' (.spec.clusterIP) to 'None' 
#       

kind: Service
apiVersion: v1
metadata:
  name: hello-service
spec:
  selector:
    app: hello-world
  ports:
  - name: port
    protocol: TCP
    port: 80
    targetPort: 8080
