apiVersion: v1
kind: Pod
metadata:
  name: hello-openshift
  labels:
    app: hello-world
spec:
  containers:
  - name: hello-openshift
    image: openshift/hello-openshift
    ports:
    - containerPort: 8080
