#
#POD:
#       - A pod represents a single instance of the application, and is the smallest 
#         compute unit in Kubernetes.
#
#       - A pod contains of one or more containers deployed together on a single host,
#         which means they share the same network space, and mount the same external storage. 
#        
#       - Pods are assigned to run on a node, and run until their containers exit or are removed.
#        

apiVersion: v1
kind: Pod
metadata:
  name: hello-openshift
  labels:
    app: hello-world
spec:
  containers:
  - name: hello-openshift
    image: openshift/hello-openshift
    ports:
    - containerPort: 8080
