#
# ReplicaSets:
#       
#       - A ReplicaSet is a controller that makes sure the specified number of pods is always running.
#       
#       - If something unexpected happens, the ReplicaSet is used to create, delete, and update the pods.
#

apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: hello-replicaset
  labels:
    app: hello-world
spec:
  replicas: 5
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-openshift
        image: openshift/hello-openshift
        ports:
        - containerPort: 8080
